import Carpenter

@available(macOS 14.0.0, *)
final class CarpenterContainer: DependencyContainer {
    static var shared: CarpenterContainer = .init()
    init() {}

    let mock_179 = Factory(Mock_179.init)
    let mock_180 = Factory(Mock_180.init)
    let mock_181 = Factory(Mock_181.init)
    let mock_183 = Factory(Mock_183.init)
    let mock_184 = Factory(Mock_184.init)
    let mock_185 = Factory(Mock_185.init)
    let mock_186 = Factory(Mock_186.init)
    let mock_187 = Factory(Mock_187.init)
    let mock_188 = Factory(Mock_188.init)
    let mock_189 = Factory(Mock_189.init)
    let mock_190 = Factory(Mock_190.init)
    let mock_164 = Factory(Mock_164.init)
    let mock_178 = Factory(Mock_178.init)
    let mock_182 = Factory(Mock_182.init)
    let mock_165 = Factory(Mock_165.init)
    let mock_176 = Factory(Mock_176.init)
    let mock_177 = Factory(Mock_177.init)
    let mock_166 = Factory(Mock_166.init)
    let mock_167 = Factory(Mock_167.init)
    let mock_168 = Factory(Mock_168.init)
    let mock_169 = Factory(Mock_169.init)
    let mock_170 = Factory(Mock_170.init)
    let mock_171 = Factory(Mock_171.init)
    let mock_172 = Factory(Mock_172.init)
    let mock_173 = Factory(Mock_173.init)
    let mock_174 = Factory(Mock_174.init)
    let mock_175 = Factory(Mock_175.init)
    let mock_150 = Factory(Mock_150.init)
    let mock_151 = Factory(Mock_151.init)
    let mock_152 = Factory(Mock_152.init)
    let mock_154 = Factory(Mock_154.init)
    let mock_156 = Factory(Mock_156.init)
    let mock_157 = Factory(Mock_157.init)
    let mock_158 = Factory(Mock_158.init)
    let mock_159 = Factory(Mock_159.init)
    let mock_160 = Factory(Mock_160.init)
    let mock_161 = Factory(Mock_161.init)
    let mock_162 = Factory(Mock_162.init)
    let mock_163 = Factory(Mock_163.init)
    let mock_134 = Factory(Mock_134.init)
    let mock_149 = Factory(Mock_149.init)
    let mock_153 = Factory(Mock_153.init)
    let mock_155 = Factory(Mock_155.init)
    let mock_135 = Factory(Mock_135.init)
    let mock_136 = Factory(Mock_136.init)
    let mock_137 = Factory(Mock_137.init)
    let mock_139 = Factory(Mock_139.init)
    let mock_140 = Factory(Mock_140.init)
    let mock_141 = Factory(Mock_141.init)
    let mock_142 = Factory(Mock_142.init)
    let mock_144 = Factory(Mock_144.init)
    let mock_145 = Factory(Mock_145.init)
    let mock_147 = Factory(Mock_147.init)
    let mock_122 = Factory(Mock_122.init)
    let mock_138 = Factory(Mock_138.init)
    let mock_143 = Factory(Mock_143.init)
    let mock_148 = Factory(Mock_148.init)
    let mock_123 = Factory(Mock_123.init)
    let mock_146 = Factory(Mock_146.init)
    let mock_125 = Factory(Mock_125.init)
    let mock_129 = Factory(Mock_129.init)
    let mock_130 = Factory(Mock_130.init)
    let mock_131 = Factory(Mock_131.init)
    let mock_132 = Factory(Mock_132.init)
    let mock_133 = Factory(Mock_133.init)
    let mock_109 = Factory(Mock_109.init)
    let mock_124 = Factory(Mock_124.init)
    let mock_126 = Factory(Mock_126.init)
    let mock_128 = Factory(Mock_128.init)
    let mock_110 = Factory(Mock_110.init)
    let mock_127 = Factory(Mock_127.init)
    let mock_111 = Factory(Mock_111.init)
    let mock_113 = Factory(Mock_113.init)
    let mock_114 = Factory(Mock_114.init)
    let mock_118 = Factory(Mock_118.init)
    let mock_120 = Factory(Mock_120.init)
    let mock_121 = Factory(Mock_121.init)
    let mock_97 = Factory(Mock_97.init)
    let mock_112 = Factory(Mock_112.init)
    let mock_115 = Factory(Mock_115.init)
    let mock_116 = Factory(Mock_116.init)
    let mock_119 = Factory(Mock_119.init)
    let mock_98 = Factory(Mock_98.init)
    let mock_117 = Factory(Mock_117.init)
    let mock_102 = Factory(Mock_102.init)
    let mock_103 = Factory(Mock_103.init)
    let mock_104 = Factory(Mock_104.init)
    let mock_105 = Factory(Mock_105.init)
    let mock_106 = Factory(Mock_106.init)
    let mock_107 = Factory(Mock_107.init)
    let mock_108 = Factory(Mock_108.init)
    let mock_85 = Factory(Mock_85.init)
    let mock_99 = Factory(Mock_99.init)
    let mock_100 = Factory(Mock_100.init)
    let mock_88 = Factory(Mock_88.init)
    let mock_89 = Factory(Mock_89.init)
    let mock_90 = Factory(Mock_90.init)
    let mock_101 = Factory(Mock_101.init)
    let mock_91 = Factory(Mock_91.init)
    let mock_93 = Factory(Mock_93.init)
    let mock_94 = Factory(Mock_94.init)
    let mock_95 = Factory(Mock_95.init)
    let mock_75 = Factory(Mock_75.init)
    let mock_86 = Factory(Mock_86.init)
    let mock_87 = Factory(Mock_87.init)
    let mock_92 = Factory(Mock_92.init)
    let mock_96 = Factory(Mock_96.init)
    let mock_76 = Factory(Mock_76.init)
    let mock_77 = Factory(Mock_77.init)
    let mock_78 = Factory(Mock_78.init)
    let mock_80 = Factory(Mock_80.init)
    let mock_81 = Factory(Mock_81.init)
    let mock_82 = Factory(Mock_82.init)
    let mock_83 = Factory(Mock_83.init)
    let mock_84 = Factory(Mock_84.init)
    let mock_64 = Factory(Mock_64.init)
    let mock_79 = Factory(Mock_79.init)
    let mock_65 = Factory(Mock_65.init)
    let mock_66 = Factory(Mock_66.init)
    let mock_67 = Factory(Mock_67.init)
    let mock_68 = Factory(Mock_68.init)
    let mock_69 = Factory(Mock_69.init)
    let mock_70 = Factory(Mock_70.init)
    let mock_71 = Factory(Mock_71.init)
    let mock_72 = Factory(Mock_72.init)
    let mock_74 = Factory(Mock_74.init)
    let mock_49 = Factory(Mock_49.init)
    let mock_52 = Factory(Mock_52.init)
    let mock_53 = Factory(Mock_53.init)
    let mock_73 = Factory(Mock_73.init)
    let mock_54 = Factory(Mock_54.init)
    let mock_55 = Factory(Mock_55.init)
    let mock_56 = Factory(Mock_56.init)
    let mock_57 = Factory(Mock_57.init)
    let mock_58 = Factory(Mock_58.init)
    let mock_59 = Factory(Mock_59.init)
    let mock_60 = Factory(Mock_60.init)
    let mock_62 = Factory(Mock_62.init)
    let mock_63 = Factory(Mock_63.init)
    let mock_35 = Factory(Mock_35.init)
    let mock_50 = Factory(Mock_50.init)
    let mock_51 = Factory(Mock_51.init)
    let mock_61 = Factory(Mock_61.init)
    let mock_36 = Factory(Mock_36.init)
    let mock_37 = Factory(Mock_37.init)
    let mock_39 = Factory(Mock_39.init)
    let mock_42 = Factory(Mock_42.init)
    let mock_43 = Factory(Mock_43.init)
    let mock_44 = Factory(Mock_44.init)
    let mock_45 = Factory(Mock_45.init)
    let mock_46 = Factory(Mock_46.init)
    let mock_47 = Factory(Mock_47.init)
    let mock_48 = Factory(Mock_48.init)
    let mock_25 = Factory(Mock_25.init)
    let mock_38 = Factory(Mock_38.init)
    let mock_40 = Factory(Mock_40.init)
    let mock_41 = Factory(Mock_41.init)
    let mock_26 = Factory(Mock_26.init)
    let mock_30 = Factory(Mock_30.init)
    let mock_31 = Factory(Mock_31.init)
    let mock_32 = Factory(Mock_32.init)
    let mock_33 = Factory(Mock_33.init)
    let mock_13 = Factory(Mock_13.init)
    let mock_27 = Factory(Mock_27.init)
    let mock_29 = Factory(Mock_29.init)
    let mock_34 = Factory(Mock_34.init)
    let mock_14 = Factory(Mock_14.init)
    let mock_28 = Factory(Mock_28.init)
    let mock_15 = Factory(Mock_15.init)
    let mock_16 = Factory(Mock_16.init)
    let mock_17 = Factory(Mock_17.init)
    let mock_18 = Factory(Mock_18.init)
    let mock_20 = Factory(Mock_20.init)
    let mock_21 = Factory(Mock_21.init)
    let mock_22 = Factory(Mock_22.init)
    let mock_23 = Factory(Mock_23.init)
    let mock_24 = Factory(Mock_24.init)
    let mock_0 = Factory(Mock_0.init)
    let mock_19 = Factory(Mock_19.init)
    let mock_1 = Factory(Mock_1.init)
    let mock_2 = Factory(Mock_2.init)
    let mock_3 = Factory(Mock_3.init)
    let mock_4 = Factory(Mock_4.init)
    let mock_5 = Factory(Mock_5.init)
    let mock_6 = Factory(Mock_6.init)
    let mock_7 = Factory(Mock_7.init)
    let mock_8 = Factory(Mock_8.init)
    let mock_9 = Factory(Mock_9.init)
    let mock_10 = Factory(Mock_10.init)
    let mock_11 = Factory(Mock_11.init)
    let mock_12 = Factory(Mock_12.init)
}

@available(macOS 14.0.0, *)
struct GeneratedByCarpenter {
    init() {}

    func makeContainer() -> Carpenter {
        var c = try! Carpenter.init {
            CarpenterContainer.allFactories
        }

        try! c.build()

        return c
    }

    func accessAllInContainer(_ container: Carpenter) {
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_179).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_180).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_181).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_183).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_184).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_185).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_186).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_187).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_188).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_189).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_190).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_164).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_178).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_182).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_165).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_176).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_177).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_166).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_167).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_168).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_169).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_170).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_171).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_172).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_173).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_174).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_175).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_150).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_151).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_152).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_154).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_156).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_157).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_158).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_159).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_160).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_161).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_162).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_163).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_134).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_149).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_153).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_155).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_135).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_136).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_137).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_139).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_140).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_141).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_142).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_144).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_145).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_147).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_122).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_138).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_143).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_148).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_123).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_146).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_125).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_129).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_130).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_131).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_132).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_133).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_109).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_124).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_126).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_128).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_110).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_127).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_111).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_113).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_114).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_118).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_120).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_121).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_97).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_112).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_115).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_116).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_119).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_98).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_117).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_102).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_103).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_104).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_105).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_106).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_107).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_108).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_85).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_99).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_100).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_88).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_89).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_90).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_101).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_91).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_93).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_94).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_95).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_75).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_86).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_87).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_92).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_96).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_76).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_77).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_78).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_80).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_81).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_82).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_83).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_84).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_64).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_79).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_65).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_66).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_67).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_68).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_69).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_70).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_71).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_72).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_74).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_49).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_52).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_53).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_73).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_54).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_55).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_56).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_57).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_58).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_59).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_60).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_62).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_63).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_35).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_50).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_51).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_61).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_36).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_37).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_39).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_42).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_43).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_44).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_45).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_46).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_47).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_48).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_25).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_38).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_40).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_41).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_26).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_30).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_31).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_32).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_33).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_13).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_27).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_29).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_34).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_14).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_28).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_15).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_16).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_17).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_18).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_20).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_21).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_22).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_23).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_24).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_0).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_19).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_1).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_2).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_3).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_4).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_5).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_6).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_7).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_8).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_9).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_10).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_11).wrappedValue)
        blackHole(GetDependency(carpenter: container, \CarpenterContainer.mock_12).wrappedValue)
    }
}
